# Generated by Django 3.2.7 on 2021-10-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email_address', models.CharField(max_length=256)),
                ('business_account', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessAccount',
        ),
    ]
