# Generated by Django 3.2.8 on 2021-11-23 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
