# Generated by Django 3.2.7 on 2021-10-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211011_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_address',
            new_name='email',
        ),
    ]
