# Generated by Django 3.2.8 on 2021-11-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_confirmed'),
        ('accounts', '0004_alter_review_date_posted'),
    ]

    operations = [
    ]
