# Generated by Django 3.2.8 on 2021-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='business_name',
            field=models.CharField(default='StudySpace', max_length=64),
        ),
    ]
