# Generated by Django 3.2.8 on 2021-10-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_review_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='wifi_rating',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
