# Generated by Django 3.2.7 on 2021-11-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(blank=True, default=' ', max_length=256),
        ),
    ]
