# Generated by Django 3.2.8 on 2021-10-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_review_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default='2021202120212021-OctOct-MonMon 1313:OctOct'),
        ),
    ]
