# Generated by Django 3.2.8 on 2021-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_review_wifi_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='charging_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comfort_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='food_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_rating',
            field=models.IntegerField(default=0),
        ),
    ]
