# Generated by Django 3.2.7 on 2021-11-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claimed_business_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_yelp_id',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
    ]
