# Generated by Django 3.2.7 on 2021-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
