# Generated by Django 3.2.7 on 2021-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211109_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_yelp_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
