# Generated by Django 3.2.7 on 2021-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_verified_yelp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='claimed_business_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
