# Generated by Django 3.2.7 on 2021-11-29 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20211129_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.CreateModel(
            name='BProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='', max_length=256)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('business_hours', models.CharField(blank=True, default='', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
