# Generated by Django 3.2.7 on 2021-11-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_claimed_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_yelp_id',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
