# Generated by Django 3.2.7 on 2021-11-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bprofile',
            name='image',
        ),
    ]
