# Generated by Django 3.2.7 on 2021-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_verified_yelp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_yelp_id',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
    ]
