# Generated by Django 3.2.7 on 2021-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_bprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
    ]
