# Generated by Django 3.2.7 on 2021-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_bprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images'),
        ),
    ]
