# Generated by Django 3.2.7 on 2021-12-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_review_review_text'),
        ('accounts', '0023_alter_bprofile_image'),
    ]

    operations = [
    ]
