# Generated by Django 3.2.8 on 2021-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20211201_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bprofile',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
